# Environment Parameters
GRID_SIZE = 4
CELL_SIZE = 50
OBSTACLE_WEIGHT = 0.2
FPS = 2000

START_COORD = (0, 0)
END_COORD = (GRID_SIZE - 1, GRID_SIZE - 1)

# Algo Parameters
SUCCESS_REWARD = 0.04
EPSILON = 0.7
GAMMA = 0.9
LEARNING_RATE = 0.1
NUM_STEPS = 100
NUM_EPISODES = 200
ACCURACY_RANGE = 20
PATH = 'Q_table.csv'

